# Convert secrets.json to Docker Compose .env file
# Usage: .\json-to-env.ps1 [-Encrypted]

param(
    [switch]$Encrypted
)

$ErrorActionPreference = "Stop"

# Determine source file
if ($Encrypted) {
    $sourceFile = "secrets.enc.json"
    Write-Host "🔓 Decrypting secrets.enc.json..."

    $keyFile = Join-Path $env:USERPROFILE ".config\sops\age\keys.txt"
    if (-not (Test-Path $keyFile)) {
        Write-Error "❌ Age key not found at: $keyFile"
        exit 1
    }

    $env:SOPS_AGE_KEY_FILE = $keyFile

    # Decrypt to temp file (run SOPS from repo root)
    $originalLocation = Get-Location
    try {
        Set-Location "../.."
        if (-not (Test-Path ".sops.yaml")) {
            throw ".sops.yaml not found in repo root"
        }
        $secretsEncPath = "infra\secrets\$sourceFile"
        # Decrypt directly to string, avoiding file encoding issues
        $decryptedJson = sops decrypt $secretsEncPath
        $config = $decryptedJson | ConvertFrom-Json
    } finally {
        Set-Location $originalLocation
    }
} else {
    $sourceFile = "secrets.json"
    if (-not (Test-Path $sourceFile)) {
        Write-Error "❌ secrets.json not found. Copy from secrets.template.json and fill in values."
        exit 1
    }
    $config = Get-Content $sourceFile | ConvertFrom-Json
}

# Output .env file path
$envFile = "..\docker\.env"

Write-Host "📝 Generating .env file from $sourceFile..."

# Generate .env content
$envContent = @"
# Generated from $sourceFile
# DO NOT EDIT THIS FILE DIRECTLY - Edit secrets.json instead

# GLM-4.6 API Configuration
OPENAI_API_KEY=$($config.GLM.ApiKey)
OPENAI_BASE_URL=$($config.GLM.BaseURL)

# Gateway Authentication
GATEWAY_TOKEN=$($config.Services.Gateway.Token)

# n8n Configuration
N8N_USER=$($config.Services.N8n.User)
N8N_PASSWORD=$($config.Services.N8n.Password)

# Optional: Model Configuration
# MODEL=$($config.GLM.Model)
# EMBEDDING_MODEL=$($config.GLM.EmbeddingModel)
"@

# Write .env file
$envContent | Out-File -Encoding utf8 $envFile

Write-Host "✅ Generated: $envFile"
Write-Host ""
Write-Host "🐳 You can now run Docker Compose:"
Write-Host "  cd ..\docker"
Write-Host "  docker compose up -d"
